# 아이리스 품종 분류
- github csv url: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv 


In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [2]:
# 1.과거의 데이터를 준비합니다.
파일경로 = '../data/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [12]:
# 원핫인코딩: pandas의 메서드
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [5]:
# 칼럼이름 출력
print(인코딩.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [6]:
# 독립변수, 종속변수
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [7]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)   # softmax 함수 사용
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',          # categorical_crossentropy 손실 함수 사용
              metrics='accuracy')

In [16]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3592 - accuracy: 0.9267
Epoch 2/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3581 - accuracy: 0.9533
Epoch 3/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3575 - accuracy: 0.9400
Epoch 4/100
5/5 [==============================] - 0s 9ms/step - loss: 0.3589 - accuracy: 0.9467
Epoch 5/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3572 - accuracy: 0.9533
Epoch 6/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3558 - accuracy: 0.9467
Epoch 7/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3554 - accuracy: 0.9467
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3544 - accuracy: 0.9533
Epoch 9/100
5/5 [==============================] - 0s 3ms/step - loss: 0.3546 - accuracy: 0.9467
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3537 - accuracy: 0.9533
Epoch 11/100
5/5 [===========

In [17]:
# 모델을 이용합니다. 
# 맨 처음 데이터 5개
print(model.predict(독립[:5]))
print(종속[:5])

# 맨 마지막 데이터 5개
print(model.predict(독립[-5:]))
print(종속[-5:])


1/1 [==============================] - 0s 18ms/step
[[9.8857903e-01 1.0863381e-02 5.5760320e-04]
 [9.7108185e-01 2.7200451e-02 1.7176720e-03]
 [9.8271894e-01 1.6333912e-02 9.4715710e-04]
 [9.7133589e-01 2.7110904e-02 1.5532067e-03]
 [9.9045765e-01 9.1000171e-03 4.4226946e-04]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
1/1 [==============================] - 0s 24ms/step
[[1.0066200e-04 1.7734146e-01 8.2255787e-01]
 [2.4014818e-04 3.0756426e-01 6.9219559e-01]
 [3.5249640e-04 3.1078804e-01 6.8885946e-01]
 [1.8404504e-04 2.2117023e-01 7.7864581e-01]
 [8.8540878e-04 4.2915910e-01 5.6995553e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0  

In [31]:
종속.columns

Index(['품종_setosa', '품종_versicolor', '품종_virginica'], dtype='object')

In [41]:
# 모델을 이용합니다.

import numpy as np

# 맨 처음 데이터 5개 ###########
prd_li = model.predict(독립[:5])

for i in range(5):
    print(i, '예측값:', 종속.columns[np.argmax(prd_li[i:i+1])])

print(종속[:5])
print()

# 마지막 데이터 5개 ############
prd_li = model.predict(독립[-5:])

for i in range(4,-1,-1):
    print(len(종속.index)-i, '예측값:', 종속.columns[np.argmax(prd_li[i:i+1])])

print(종속[-5:])


1/1 [==============================] - 0s 18ms/step
0 예측값: 품종_setosa
1 예측값: 품종_setosa
2 예측값: 품종_setosa
3 예측값: 품종_setosa
4 예측값: 품종_setosa
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0

1/1 [==============================] - 0s 20ms/step
146 예측값: 품종_virginica
147 예측값: 품종_virginica
148 예측값: 품종_virginica
149 예측값: 품종_virginica
150 예측값: 품종_virginica
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [42]:
# weights & bias 출력
print(model.get_weights())

[array([[ 0.00692811, -0.05106262,  0.04293052],
       [ 1.4178632 , -0.4303287 , -0.8824086 ],
       [-1.1240761 ,  0.5145473 ,  0.2751001 ],
       [-2.7576056 , -0.41148365,  1.9872388 ]], dtype=float32), array([ 1.31186  ,  0.8021161, -1.2089928], dtype=float32)]
