# 히든레이어

- 보스턴 집값 예측: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv

- 아이리스 품종 분류: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv 


In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

## 보스턴 집값 예측

In [3]:
# 1.과거의 데이터를 준비합니다.
파일경로 = '../data/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)

# 종속변수, 독립변수
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [9]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)    # 히든 레이어 활성화 함수로 swish - 성능이 좋은 활성화 함수(3년전) / 우리는 relu를 주로 배웠다.
Y = tf.keras.layers.Dense(1)(H)                         # X 대신 H 넣는 것 주의
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse', metrics='accuracy')

In [10]:
# 모델 구조 확인
model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 13)]              0         
                                                                 
 dense_2 (Dense)             (None, 10)                140       
                                                                 
 dense_3 (Dense)             (None, 1)                 11        
                                                                 
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [14]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=100)

Epoch 1/100
16/16 [==============================] - 0s 1ms/step - loss: 28.9684 - accuracy: 0.0000e+00
Epoch 2/100
16/16 [==============================] - 0s 1ms/step - loss: 29.3459 - accuracy: 0.0000e+00
Epoch 3/100
16/16 [==============================] - 0s 1ms/step - loss: 30.2215 - accuracy: 0.0000e+00
Epoch 4/100
16/16 [==============================] - 0s 2ms/step - loss: 30.4726 - accuracy: 0.0000e+00
Epoch 5/100
16/16 [==============================] - 0s 2ms/step - loss: 28.5052 - accuracy: 0.0000e+00
Epoch 6/100
16/16 [==============================] - 0s 2ms/step - loss: 28.5950 - accuracy: 0.0000e+00
Epoch 7/100
16/16 [==============================] - 0s 1ms/step - loss: 29.9742 - accuracy: 0.0000e+00
Epoch 8/100
16/16 [==============================] - 0s 1ms/step - loss: 31.0738 - accuracy: 0.0000e+00
Epoch 9/100
16/16 [==============================] - 0s 4ms/step - loss: 30.1555 - accuracy: 0.0000e+00
Epoch 10/100
16/16 [==============================] - 0s 2ms/ste

In [15]:
# 4. 모델을 이용합니다
print(model.predict(독립[:5]))
print(종속[:5])

1/1 [==============================] - 0s 73ms/step
[[32.65705 ]
 [27.135525]
 [31.77218 ]
 [31.033075]
 [29.768278]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


## 아이리스 품종 분류


In [17]:
# 1.과거의 데이터를 준비합니다.
파일경로 = '../data/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)

# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [18]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [19]:
# 모델 구조 확인
model.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 4)]               0         
                                                                 
 dense_4 (Dense)             (None, 8)                 40        
                                                                 
 dense_5 (Dense)             (None, 8)                 72        
                                                                 
 dense_6 (Dense)             (None, 8)                 72        
                                                                 
 dense_7 (Dense)             (None, 3)                 27        
                                                                 
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000)

In [21]:
# 4. 모델을 이용합니다
print(model.predict(독립[0:5]))
print(종속[0:5])

1/1 [==============================] - 0s 73ms/step
[[9.9999988e-01 3.4074584e-16 1.4177157e-07]
 [1.0000000e+00 1.1370503e-14 3.0524998e-08]
 [1.0000000e+00 2.4423566e-15 5.2149378e-08]
 [1.0000000e+00 2.2300529e-14 1.7965293e-09]
 [9.9999988e-01 2.2380956e-16 9.2627005e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
